import type { SupabaseClient } from "@supabase/supabase-js";
import { getOrCreateCart, clearCart } from "@/services/cart";
import { computeTotals } from "@/services/cart/totals";
import { evaluateCoupon } from "@/services/marketing/coupons";
import type { CartTotals } from "@/services/types";

export interface CheckoutInput {
  customerId: string;
  storeId: string;
  fulfillmentMode: "delivery" | "drive" | "pickup";
  slotId?: string | null;
  scheduledStart?: string | null;
  scheduledEnd?: string | null;
  addressSnapshot?: Record<string, unknown> | null;
  deliveryFee?: number;
  paymentMethod: "cash_on_delivery" | "card_on_delivery" | "card_online" | "edahabia" | "cib" | "wallet";
  notes?: string | null;
}

export interface PlaceOrderResult {
  orderId: string;
  orderNumber: string;
  totals: CartTotals;
}

/**
 * Place an order from the current cart in a single transactional call.
 * The `service_role` client is required (bypasses RLS) so that we can
 * insert into `orders`, `order_items`, `deliveries`, `inventory_movements`
 * and `payments` atomically.
 *
 * A dedicated Postgres function `place_order(json)` would be even
 * safer for concurrency; that upgrade is planned when Phase 3 wires
 * the dispatch pipeline.
 */
export async function placeOrder(
  sb: SupabaseClient,
  input: CheckoutInput,
): Promise<PlaceOrderResult> {
  const cart = await getOrCreateCart(sb, {
    customerId: input.customerId,
    storeId: input.storeId,
  });

  if (cart.items.length === 0) throw new Error("Panier vide");

  let deliveryFee = input.fulfillmentMode === "delivery" ? input.deliveryFee ?? 250 : 0;
  let discount = 0;
  let couponId: string | null = null;

  // Apply coupon (if any) — recomputed server-side to close the loophole
  // where a client-side amount could be spoofed.
  if (cart.coupon_code) {
    const subtotalOnly = computeTotals(cart.items).subtotal;
    const res = await evaluateCoupon(sb, cart.coupon_code, subtotalOnly, input.customerId);
    if (res.valid) {
      discount = res.amountOff;
      if (res.freeShipping) deliveryFee = 0;
      couponId = res.couponId;
    }
  }

  const totals = computeTotals(cart.items, { deliveryFee, discount });

  // 1. Create the order (order_number auto-generated by trigger)
  const { data: order, error: orderErr } = await sb
    .from("orders")
    .insert({
      customer_id: input.customerId,
      store_id: input.storeId,
      status: "pending",
      fulfillment_mode: input.fulfillmentMode,
      slot_id: input.slotId ?? null,
      scheduled_start: input.scheduledStart ?? null,
      scheduled_end: input.scheduledEnd ?? null,
      address_snapshot: input.addressSnapshot ?? null,
      currency: "DZD",
      subtotal: totals.subtotal,
      discount_total: totals.discount,
      delivery_fee: totals.delivery_fee,
      tax_total: totals.tax,
      total: totals.total,
      notes: input.notes ?? null,
    })
    .select("id, order_number")
    .single();
  if (orderErr) throw orderErr;

  // 2. Insert order items (product snapshot for audit)
  const orderItems = cart.items.map((it) => ({
    order_id: order.id,
    product_id: it.product_id,
    product_snapshot: {
      sku: it.product?.sku,
      name: it.product?.name_fr,
      unit: it.product?.unit,
      image_url: it.product?.images?.[0] ?? null,
    },
    quantity: it.quantity,
    unit_price: Number(it.product?.promo_price ?? it.unit_price),
    discount: 0,
    total: Number(it.product?.promo_price ?? it.unit_price) * it.quantity,
  }));
  const { error: itemsErr } = await sb.from("order_items").insert(orderItems);
  if (itemsErr) throw itemsErr;

  // 3. Reserve stock (append inventory movements)
  const movements = cart.items.map((it) => ({
    store_id: input.storeId,
    product_id: it.product_id,
    type: "reserve" as const,
    quantity: it.quantity,
    reference_id: order.id,
    reference_type: "order",
    reason: `Reserved for order ${order.order_number}`,
  }));
  await sb.from("inventory_movements").insert(movements);

  // 4. Register payment intent (real capture happens later via PSP webhook)
  await sb.from("payments").insert({
    order_id: order.id,
    method: input.paymentMethod,
    status: input.paymentMethod === "cash_on_delivery" ? "pending" : "pending",
    amount: totals.total,
    currency: "DZD",
  });

  // 5. Log the coupon redemption if one applied
  if (couponId && discount > 0) {
    await sb.from("coupon_redemptions").insert({
      coupon_id: couponId,
      customer_id: input.customerId,
      order_id: order.id,
      amount_off: discount,
    });
  }

  // 6. Clear the cart
  await clearCart(sb, cart.id);

  return {
    orderId: order.id,
    orderNumber: order.order_number,
    totals,
  };
}
