/**
 * Placeholder — this file is auto-generated by:
 *   pnpm db:types
 *
 * After running the initial Supabase migration, generate the real types
 * with the command above. Until then, the type is a permissive `any`
 * shape so the app compiles.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;
